# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 276447e80f806aafba54588923c675ee05604f63276593f36a8a2bc33815ab1f7da028f809833b0576d245311454dbfe102e92dfbfe86c853c9faeda9d607077

test:
  secret_key_base: ac7f3363ac666aa262d4a498d47060a95ae80e8bc08ed4b1a3c458cf0e635bbfea21957b72366ae1f5a73dfd31f8f720595ae14d86998c92acd388490179b6f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
